### PR TITLE
New segments to show return code of last command

### PR DESCRIPTION
**Pull request by dflock**
- Added new segment code in segments/rc.bash
- Added settings to default.settings
- Added import to helpers/import.bash

Looks like this:

image

### CODE REVIEW

**Comment by brujoand** [comment]
Nice, this looks usefull :+1: Maybe we should go for a more intuitive name though, what do you think about exitcode or resultcode?

**Comment by dflock** [comment]
I could go for `return_code`, if you want something more explicit? Shall I change it in the branch?

**Comment by brujoand** [comment]
Sounds good. Yeah the rest looks good to me.

**Comment by dflock** [comment]
Ok, done.

**Comment by dflock** [comment]
Oops. forgot the vars, hang on...

**Comment by dflock** [comment]
Ok, really done now.

**Comment by brujoand** [comment]
Great, thanks!

**Pull request merged**
